// demos/showcase/src/app/app.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';
import * as PXBColors from '@pxblue/colors';
// eslint-disable-next-line @typescript-eslint/no-var-requires
const iconSet = require('@pxblue/icons-svg/icons.svg');

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
    encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
    drawerBodyTestItems;
    colors: Record<string, any>;
    constructor(private readonly matIconRegistry: MatIconRegistry, private readonly domSanitizer: DomSanitizer) {
        this.colors = PXBColors;
        this.matIconRegistry.addSvgIconSetInNamespace(
            'px-icons',
            this.domSanitizer.bypassSecurityTrustResourceUrl(iconSet)
        );

        this.drawerBodyTestItems = [
            {
                title: 'First DrawerNavGroup',
                items: [
                    {
                        statusColor: this.colors.red[500],
                        title: 'DrawerNavItem 1'
                    },
                    {
                        statusColor: this.colors.blue[500],
                        title: 'DrawerNavItem 2'
                    }
                ]
            },
            {
                title: 'Second DrawerNavGroup',
                items: [
                    {
                        title: 'DrawerNavItem 3'
                    },
                    {
                        statusColor: this.colors.orange[500],
                        title: 'DrawerNavItem 4'
                    }
                ]
            }
        ]
    }

    test(): void {
        // eslint-disable-next-line no-alert
        alert('Hero component');
    }

    clickDrawerHeaderButton(): void {
        // eslint-disable-next-line
        console.log('drawer header button clicked...');
    }
}

<pxb-drawer-layout [variant]="getVariant()" (backdropClick)="closeDrawer()"
                   [dir]="isRtl ? 'rtl' : 'ltr'"
                   [class.rtl]="isRtl">
    <showcase-drawer pxb-drawer></showcase-drawer>
    <div pxb-content>
        <mat-toolbar class="toolbar">
            <button *ngIf="isMobile()" mat-icon-button class="menu-icon" (click)="openDrawer()">
                <mat-icon>menu</mat-icon>
            </button>
            <h2>Showcase</h2>
            <pxb-spacer></pxb-spacer>
            <button mat-icon-button style="margin: 0px 8px" (click)="toggleTheme()">
              <mat-icon>invert_colors</mat-icon>
            </button>
            <button mat-icon-button style="margin: 0px 8px" (click)="toggleDirectionality()">
              <mat-icon>compare_arrows</mat-icon>
            </button>
            <pxb-user-menu
                style="margin: 0px 8px"
                avatarValue="MS"
                menuTitle="Marshall Sutter"
                menuSubtitle="msutter@acmesteel.com"
                [(open)]="userMenuOpen"
            >
                <mat-nav-list pxb-menu-body [style.paddingTop.px]="0">
                    <div *ngFor="let group of menuGroups">
                        <ng-container *ngIf="group.title">
                            <mat-divider></mat-divider>
                            <div style="padding: 8px 24px 8px 24px; font-weight: 600">{{ group.title }}</div>
                            <mat-divider></mat-divider>
                        </ng-container>
                        <pxb-info-list-item
                            *ngFor="let item of group.items"
                            [dense]="true"
                            (click)="userMenuOpen = false"
                        >
                            <mat-icon pxb-icon>{{ item.icon }}</mat-icon>
                            <div pxb-title>{{ item.title }}</div>
                        </pxb-info-list-item>
                    </div>
                </mat-nav-list>
            </pxb-user-menu>
        </mat-toolbar>
        <div style="padding: 24px">
            <div class="scorecards">
                <pxb-score-card
                    class="red-score-card"
                    [headerTitle]="'Substation 3'"
                    [headerSubtitle]="'High Humidity Alarm'"
                    [headerInfo]="'4 Devices'"
                >
                    <mat-icon pxb-action-items>more_vert</mat-icon>
                    <mat-list pxb-body>
                        <pxb-info-list-item dense="true" [style.color]="colors.red[500]" class="card-body-item">
                            <div pxb-title>1 Alarm</div>
                            <mat-icon pxb-icon>notifications</mat-icon>
                        </pxb-info-list-item>
                        <pxb-info-list-item dense="true" [style.color]="colors.blue[500]" class="card-body-item">
                            <div pxb-title>1 Event</div>
                            <mat-icon pxb-icon>list_alt</mat-icon>
                        </pxb-info-list-item>
                        <pxb-info-list-item dense="true" class="card-body-item">
                            <div pxb-title>Online</div>
                            <mat-icon pxb-icon>cloud</mat-icon>
                        </pxb-info-list-item>
                    </mat-list>
                    <pxb-hero-banner pxb-badge>
                        <pxb-hero [label]="'Temperature'" [value]="98" [units]="'°F'" [iconSize]="36">
                            <mat-icon svgIcon="px-icons:temp" pxb-primary></mat-icon>
                        </pxb-hero>
                        <pxb-hero [label]="'Humidity'" [value]="'54'" [units]="'%'" [iconSize]="36">
                            <mat-icon
                                svgIcon="px-icons:moisture"
                                pxb-primary
                                [style.color]="colors.blue[300]"
                            ></mat-icon>
                        </pxb-hero>
                    </pxb-hero-banner>
                    <pxb-info-list-item hidePadding="true" dense="true" pxb-action-row>
                        <div pxb-title>More</div>
                        <mat-icon mat-list-icon pxb-right-content>chevron_right</mat-icon>
                    </pxb-info-list-item>
                </pxb-score-card>

                <pxb-score-card
                    [headerTitle]="'Substation 3'"
                    [headerSubtitle]="'Normal'"
                    [headerInfo]="'4 Devices'"
                    [badgeOffset]="-92"
                >
                    <mat-icon pxb-action-items>more_vert</mat-icon>
                    <mat-list pxb-body>
                        <pxb-info-list-item dense="true" class="card-body-item">
                            <div pxb-title>0 Alarms</div>
                            <mat-icon pxb-icon>notifications</mat-icon>
                        </pxb-info-list-item>
                        <pxb-info-list-item dense="true" [style.color]="colors.blue[500]" class="card-body-item">
                            <div pxb-title>1 Event</div>
                            <mat-icon pxb-icon>list_alt</mat-icon>
                        </pxb-info-list-item>
                        <pxb-info-list-item dense="true" class="card-body-item">
                            <div pxb-title>Online</div>
                            <mat-icon pxb-icon>cloud</mat-icon>
                        </pxb-info-list-item>
                    </mat-list>
                    <pxb-hero
                        pxb-badge
                        label="Health"
                        value="98"
                        units="%"
                        [iconBackgroundColor]="colors.white[50]"
                        (click)="test()"
                        style="cursor: pointer"
                        [iconSize]="72"
                    >
                        <mat-icon svgIcon="px-icons:grade_a" pxb-primary [style.color]="colors.green[500]"></mat-icon>
                    </pxb-hero>
                    <pxb-info-list-item hidePadding="true" dense="true" pxb-action-row>
                        <div pxb-title>View Location</div>
                        <mat-icon mat-list-icon pxb-right-content>chevron_right</mat-icon>
                    </pxb-info-list-item>
                </pxb-score-card>
            </div>

            <mat-card class="container-card">
                <mat-list style="padding: 0">
                    <pxb-hero-banner [divider]="true">
                        <pxb-hero
                            label="Healthy"
                            value="96"
                            units="/100"
                            (click)="test()"
                            style="cursor: pointer"
                            [iconSize]="36"
                        >
                            <mat-icon
                                svgIcon="px-icons:grade_a"
                                pxb-primary
                                [style.color]="colors.green[500]"
                            ></mat-icon>
                        </pxb-hero>

                        <pxb-hero label="Load">
                            <pie-progress class="progress-icon" percent="65" size="36" pxb-primary></pie-progress>
                            <pxb-channel-value value="65" units="%">
                                <mat-icon [style.color]="colors.red['500']">trending_up</mat-icon>
                            </pxb-channel-value>
                        </pxb-hero>

                        <pxb-hero label="Estimated">
                            <mat-icon pxb-primary>timer</mat-icon>
                            <pxb-channel-value value="1" units="h"></pxb-channel-value>
                            <pxb-channel-value value="26" units="m"></pxb-channel-value>
                        </pxb-hero>

                        <pxb-hero label="Battery" value="Full">
                            <battery-progress
                                class="progress-icon"
                                percent="90"
                                size="36"
                                pxb-primary
                            ></battery-progress>
                        </pxb-hero>
                    </pxb-hero-banner>
                </mat-list>

                <pxb-info-list-item
                    divider="full"
                    dense="true"
                    [style.color]="colors.green[500]"
                    [statusColor]="colors.green[500]"
                >
                    <div pxb-title>Status</div>
                    <mat-icon pxb-icon svgIcon="px-icons:leaf" [style.color]="colors.green[500]"></mat-icon>
                    <pxb-channel-value pxb-right-content value="Online, ESS+"></pxb-channel-value>
                </pxb-info-list-item>

                <pxb-info-list-item divider="full" [subtitle]="['Phase A', 'Phase B', 'Phase C']" [avatar]="true">
                    <div pxb-title>Input Voltage</div>
                    <mat-icon
                        pxb-icon
                        svgIcon="px-icons:voltage_circled"
                        [style.backgroundColor]="colors.black[500]"
                        [style.color]="colors.white[50]"
                    ></mat-icon>
                    <div pxb-right-content>
                        <pxb-channel-value value="478" units="V"></pxb-channel-value>,
                        <pxb-channel-value value="479" units="V"></pxb-channel-value>,
                        <pxb-channel-value value="473" units="V"></pxb-channel-value>
                    </div>
                </pxb-info-list-item>

                <div class="error">
                    <pxb-info-list-item
                        divider="full"
                        [avatar]="true"
                        [subtitle]="['Phase A', 'Phase B', 'Phase C']"
                        [statusColor]="colors.red[500]"
                    >
                        <div pxb-title>Output Voltage</div>
                        <mat-icon
                            pxb-icon
                            svgIcon="px-icons:voltage_circled"
                            [style.color]="colors.white[50]"
                            [style.backgroundColor]="colors.red[500]"
                        ></mat-icon>

                        <div pxb-right-content [style.color]="colors.black[500]">
                            <pxb-list-item-tag class="tag-label" label="monitored"></pxb-list-item-tag>
                            <pxb-channel-value value="480" units="V"></pxb-channel-value>,
                            <pxb-channel-value value="480" units="V"></pxb-channel-value>,
                            <pxb-channel-value value="480" units="V"></pxb-channel-value>
                        </div>
                    </pxb-info-list-item>
                </div>

                <pxb-info-list-item divider="full" dense="true">
                    <div pxb-title>Output Voltage</div>
                    <mat-icon pxb-icon svgIcon="px-icons:current_circled"></mat-icon>
                    <div pxb-right-content>
                        <pxb-channel-value value="15" units="A"></pxb-channel-value>,
                        <pxb-channel-value value="15" units="A"></pxb-channel-value>,
                        <pxb-channel-value value="14.9" units="A"></pxb-channel-value>
                    </div>
                </pxb-info-list-item>

                <pxb-info-list-item dense="true">
                    <div pxb-title>Temperature</div>
                    <mat-icon pxb-icon svgIcon="px-icons:temp"></mat-icon>
                    <div pxb-right-content>
                        <pxb-list-item-tag
                            class="tag-label"
                            label="Active"
                            [fontColor]="colors.green[500]"
                            [backgroundColor]="colors.white[300]"
                        ></pxb-list-item-tag>
                        <pxb-list-item-tag
                            class="tag-label"
                            label="Overheat"
                            [fontColor]="colors.white[50]"
                            [backgroundColor]="colors.red[500]"
                        ></pxb-list-item-tag>
                        <pxb-channel-value value="68" units="°F">
                            <mat-icon [style.color]="colors.red['500']">trending_up</mat-icon>
                        </pxb-channel-value>
                    </div>
                </pxb-info-list-item>
            </mat-card>

            <mat-card class="container-card" style="margin-top: 10px; margin-bottom: 24px; padding: 16px;">
                <pxb-empty-state title="No Devices" description="Consult your local admin for details">
                    <mat-icon pxb-empty-icon>devices</mat-icon>
                    <button mat-raised-button color="primary" pxb-actions>
                        <mat-icon>add_circle</mat-icon>
                        ADD DEVICE
                    </button>
                </pxb-empty-state>
            </mat-card>
        </div>
    </div>
</pxb-drawer-layout>

// react/component-demo/showcase/src/App.js
import React from 'react';
import Hero from '@pxblue/react-components/core/Hero';
import HeroBanner from '@pxblue/react-components/core/HeroBanner';
import ChannelValue from '@pxblue/react-components/core/ChannelValue';
import EmptyState from '@pxblue/react-components/core/EmptyState';
import InfoListItem from '@pxblue/react-components/core/InfoListItem';
import ScoreCard from '@pxblue/react-components/core/ScoreCard';

import DevicesIcon from '@material-ui/icons/Devices'
import { Add } from '@material-ui/icons'

import Trend from '@material-ui/icons/TrendingUp';
import Timer from '@material-ui/icons/Timer';

import { List, Card, ListItem, ListItemText, ListItemSecondaryAction } from '@material-ui/core';
import { ChevronRight, MoreVert } from '@material-ui/icons';
import * as Colors from '@pxblue/colors';
import { Pie, Battery } from '@pxblue/react-progress-icons';
import { GradeA, Leaf, CurrentCircled, VoltageCircled, Temp, Moisture as Humidity } from '@pxblue/icons-mui';
import Button from "@material-ui/core/Button";

import top from './topology_40.png';

export default () => (
    <div style={{ padding: 10 }}>
        <div style={{ display: 'flex', flexWrap: 'wrap' }}>
            <ScoreCard
                style={{ maxWidth: 400 }}
                headerColor={Colors.red[500]}
                headerBackgroundImage={top}
                headerTitle={'Substation 3'}
                headerSubtitle={'High Humidity Alarm'}
                headerInfo={'4 Devices'}
                headerFontColor={Colors.white[50]}
                actionItems={[
                    <MoreVert onClick={() => alert('something did')} />,
                ]}
                badge={
                    <HeroBanner style={{ minWidth: 210 }}>
                        <Hero
                            icon={<Temp fontSize={'inherit'} htmlColor={Colors.black[500]} />}
                            label={'Temperature'}
                            iconSize={48}
                            value={98}
                            units={'°F'}
                            fontSize={'normal'}
                        />
                        <Hero
                            icon={<Humidity fontSize={'inherit'} htmlColor={Colors.blue[300]} />}
                            label={'Humidity'}
                            value={54}
                            units={'%'}
                            iconSize={48}
                            fontSize={'normal'}
                        />
                    </HeroBanner>
                }
                badgeOffset={0}
                actionRow={
                    <List style={{margin: 0}}>
                        <ListItem>
                            <ListItemText primary="View Location" />
                            <ListItemSecondaryAction> <ChevronRight /> </ListItemSecondaryAction>
                        </ListItem>
                    </List>
                }
            >
                <List style={{ padding: '16px 0' }}>
                    <InfoListItem dense style={{ height: 36 }}
                        fontColor={Colors.red[500]}
                        iconColor={Colors.red[500]}
                        title={'1 Alarm'}
                        icon={<Leaf color={'inherit'} />}
                    />
                    <InfoListItem dense style={{ height: 36 }}
                        fontColor={Colors.blue[500]}
                        iconColor={Colors.blue[500]}
                        title={'1 Event'}
                        icon={<Leaf color={'inherit'} />}
                    />
                    <InfoListItem dense style={{ height: 36 }}
                        title={'Online'}
                        icon={<Leaf color={'inherit'} />}
                    />
                </List>
            </ScoreCard>
            <ScoreCard
                style={{ flex: '1 1 0px', maxWidth: 400, marginLeft: 10 }}
                headerColor={Colors.blue[500]}
                headerBackgroundImage={top}
                headerTitle={'Substation 3'}
                headerSubtitle={'Normal'}
                headerInfo={'4 Devices'}
                headerFontColor={Colors.white[50]}
                actionItems={[
                    <MoreVert onClick={() => alert('something did')} />,
                ]}
                badge={
                    <HeroBanner>
                        <Hero
                            icon={<GradeA fontSize={'inherit'} htmlColor={Colors.green[500]} />}
                            iconBackgroundColor={Colors.white[50]}
                            label={'Health'}
                            iconSize={72}
                            value={98}
                            units={'%'}
                            fontSize={'normal'}
                        />
                    </HeroBanner>
                }
                badgeOffset={-52}
                actionRow={
                    <List style={{margin: 0}}>
                        <ListItem>
                            <ListItemText primary="View Location" />
                            <ListItemSecondaryAction> <ChevronRight /> </ListItemSecondaryAction>
                        </ListItem>
                    </List>
                }
            >
                <List style={{ padding: '16px 0' }}>
                    <InfoListItem dense style={{ height: 36 }}
                        title={'0 Alarms'}
                        icon={<Leaf color={'inherit'} />}
                    />
                    <InfoListItem dense style={{ height: 36 }}
                        fontColor={Colors.blue[500]}
                        iconColor={Colors.blue[500]}
                        title={'1 Event'}
                        icon={<Leaf color={'inherit'} />}
                    />
                    <InfoListItem dense style={{ height: 36 }}
                        title={'Online'}
                        icon={<Leaf color={'inherit'} />}
                    />
                </List>
            </ScoreCard>

        </div>

        <Card style={{ marginTop: 10 }}>
            <List style={{ color: Colors.gray['800'], padding: 0 }}>
                <HeroBanner divider>
                    <Hero
                        icon={<GradeA fontSize={'inherit'} color={'inherit'} htmlColor={Colors.green[500]} />}
                        label={'Healthy'}
                        value={96}
                        units={'/100'}
                        fontSize={'normal'}
                    />
                    <Hero
                        icon={<Pie color={Colors.blue[500]} percent={65} size={36} />}
                        label={'Load'}
                        fontSize={'normal'}
                    >
                        <ChannelValue value={65} units={'%'}
                            icon={<Trend htmlColor={Colors.red[500]} fontSize={'inherit'} />} />
                    </Hero>
                    <Hero
                        icon={<Timer fontSize={'inherit'} color={'inherit'} />}
                        label={'Estimated'}
                        fontSize={'normal'}
                    >
                        <ChannelValue value={1} units={'h'} />
                        <ChannelValue value={26} units={'m'} />
                    </Hero>
                    <Hero
                        icon={<Battery color={Colors.blue[500]} percent={100} size={36} />}
                        value={'Full'}
                        label={'Battery'}
                        fontSize={'normal'}
                    >
                        <ChannelValue value={'Full'} />
                    </Hero>
                </HeroBanner>
                <InfoListItem dense
                    title={'Status'}
                    divider={'full'}
                    statusColor={Colors.green[500]}
                    subtitleSeparator={'/'}
                    icon={<Leaf color={'inherit'} />}
                    rightComponent={<ChannelValue fontSize={16} value={'Online, ESS+'} />}
                />
                <InfoListItem
                    title={'Input Voltage'}
                    divider={'full'}
                    avatar
                    subtitle={['Phase A', 'Phase B', 'Phase C']}
                    icon={<VoltageCircled />}
                    rightComponent={<span><ChannelValue fontSize={16} value={478} units={'V'} />, <ChannelValue fontSize={16} value={479} units={'V'} />, <ChannelValue fontSize={16} value={473} units={'V'} /></span>}
                />
                <InfoListItem
                    title={'Output Voltage'}
                    divider={'full'}
                    avatar
                    statusColor={Colors.red[500]}
                    fontColor={Colors.red[500]}
                    subtitle={['Phase A', 'Phase B', 'Phase C']}
                    icon={<VoltageCircled color={'inherit'} />}
                    rightComponent={<span style={{ color: Colors.red[500] }}><ChannelValue fontSize={16} value={480} units={'V'} />, <ChannelValue fontSize={16} value={480} units={'V'} />, <ChannelValue fontSize={16} value={480} units={'V'} /></span>}
                />
                <InfoListItem dense
                    title={'Output Current'}
                    divider={'full'}
                    icon={<CurrentCircled color={'inherit'} />}
                    rightComponent={<span><ChannelValue fontSize={16} value={15} units={'A'} />, <ChannelValue fontSize={16} value={14.9} units={'A'} />, <ChannelValue fontSize={16} value={15} units={'A'} /></span>}
                />
                <InfoListItem dense
                    title={'Temperature'}
                    divider={'full'}
                    icon={<Temp />}
                    rightComponent={<ChannelValue fontSize={16} icon={<Trend htmlColor={Colors.red[500]} />} value={68} units={'°F'} />}
                />
            </List>
        </Card>
        <Card style={{ marginTop: '10px', padding: '10px' }}>
            <EmptyState
                icon={
                    <DevicesIcon fontSize={'inherit'} />
                }
                title={"No Devices"}
                actions={
                    <Button variant="contained" color="primary">
                        <Add style={{ marginRight: '5px' }} />
                        Add Device
                    </Button>
                }
            />
        </Card>
    </div >
);
