// projects/component-demo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'component-demo';
}

<mat-card>
  <mat-list>
    <hero-banner [divider]="true" >
      <hero [allowClick]="true" label="Healthy" value="96"  units="/100" [secondaryIcon]="true" fontSize="small" >
        <mat-icon svgIcon="px-icons:bearing" primary></mat-icon>
        <mat-icon secondary class="output" >trending_up</mat-icon>
        
      </hero>

      <hero [allowClick]="true" label="Load" fontSize="small" >
        <pie-progress class="progress-icon" percent="70" size="36" primary></pie-progress>
        <channel-value class="content" value="65" [secondaryIcon]="true" units="%" [prefix]="true" fontSize="small" >
          <mat-icon secondary class="output">trending_up</mat-icon>
        </channel-value>
      </hero>

      <hero [allowClick]="true" label="Estimated" >
        <mat-icon primary>alarm</mat-icon>
        <channel-value class="content" value="1" units="h"></channel-value>
        <channel-value class="content" value="26" units="m"></channel-value>
      </hero>

      <hero [allowClick]="true" label="Battery"   value="Full" fontSize="small">
        <battery-progress class="progress-icon" percent="90" size="36" primary></battery-progress>
      </hero>

    </hero-banner>
  </mat-list>

  <mat-list >
    <mat-list-item >
        <mat-icon mat-list-icon  svgIcon="px-icons:leaf" class="list-icon"></mat-icon>
      <h4 mat-line>status</h4>
      <div class="channelcontent"> 
          <channel-value class="content list-value" value="online,ESS+"></channel-value>
      </div>
        
    </mat-list-item>
    <mat-divider></mat-divider>

    <mat-list-item >
        <mat-icon mat-list-icon svgIcon="px-icons:voltage_circled" class="list-icon"></mat-icon>
        <h4 mat-line>Input Voltage</h4>
        <div class="channelcontent">
        <channel-value class="content list-value" value="478" units="V"></channel-value>,
        <channel-value class="content list-value" value="479" units="V"></channel-value>,
        <channel-value class="content list-value" value="473" units="V"></channel-value>
        </div>
      </mat-list-item>
      <mat-divider></mat-divider>

    <mat-list-item class="output">
        <mat-icon mat-list-icon svgIcon="px-icons:voltage_circled" class="list-icon" color="red"></mat-icon>
        <h4 mat-line>Output Voltage</h4>
        <div class="channelcontent">
        <channel-value class="content list-value" value="480" units="V"></channel-value>,
        <channel-value class="content list-value" value="480" units="V"></channel-value>,
        <channel-value class="content list-value" value="480" units="V"></channel-value>
        </div>
      </mat-list-item>
      <mat-divider></mat-divider>

    <mat-list-item >
        <mat-icon mat-list-icon svgIcon="px-icons:current_circled" class="list-icon" color="red"></mat-icon>
        <h4 mat-line>Output Current</h4>
        <div class="channelcontent">
        <channel-value class="content list-value" value="15" units="A"></channel-value>,
        <channel-value class="content list-value" value="15" units="A"></channel-value>,
        <channel-value class="content list-value" value="15" units="A"></channel-value>
        </div>
      </mat-list-item>
      <mat-divider></mat-divider>

      <mat-list-item >
          <mat-icon mat-list-icon svgIcon="px-icons:temp" class="list-icon" color="red"></mat-icon>
          <h4 mat-line>Temperature</h4>
          <div class="channelcontent">
          <channel-value class="content" value="68" [secondaryIcon]="true" units="°F">
              <mat-icon secondary>trending_up</mat-icon>
            </channel-value>
          </div>
        </mat-list-item>
  </mat-list>


</mat-card>

// react/component-demo/src/App.js
import React from 'react';
import Hero from '@pxblue/react-components/core/Hero';
import HeroBanner from '@pxblue/react-components/core/HeroBanner';
import ChannelValue from '@pxblue/react-components/core/ChannelValue';
import Trend from '@material-ui/icons/TrendingUp';
import Timer from '@material-ui/icons/Timer';

import { List, ListItem, ListItemIcon, ListItemText, Card } from '@material-ui/core';
import * as Colors from '@pxblue/colors';
import { Pie, Battery } from '@pxblue/react-progress-icons';
import { GradeA, Leaf, CurrentCircled, VoltageCircled, Temp } from '@pxblue/icons-mui';


export default ({ ...props }) => (
    <Card>
        <List style={{color: Colors.gray['800'], padding: 0}}>
            <HeroBanner divider>
                <Hero
                    icon={<GradeA fontSize={'inherit'} color={'inherit'} nativeColor={Colors.green[500]} />}
                    label={'Healthy'}
                    value={96}
                    units={'/100'}
                    fontSize={'normal'}
                />
                <Hero
                    icon={<Pie color={Colors.blue[500]} percent={65} size={36} />}
                    label={'Load'}
                    fontSize={'normal'}
                >
                    <ChannelValue value={65} units={'%'} icon={<Trend nativeColor={Colors.red[500]} fontSize={'inherit'} />} />
                </Hero>
                <Hero
                    icon={<Timer fontSize={'inherit'} color={'inherit'} />}
                    label={'Estimated'}
                    fontSize={'normal'}
                >
                    <ChannelValue value={1} units={'h'} />
                    <ChannelValue value={26} units={'m'} />
                </Hero>
                <Hero
                    icon={<Battery color={Colors.blue[500]} percent={100} size={36} />}
                    value={'Full'}
                    label={'Battery'}
                    fontSize={'normal'}
                >
                    <ChannelValue value={'Full'} />
                </Hero>
            </HeroBanner>
            <ListItem divider>
                <ListItemIcon><Leaf/></ListItemIcon>
                <ListItemText primary={'Status'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                    primary={<ChannelValue value={'Online, ESS+'} />} 
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
            <ListItem divider>
                <ListItemIcon><VoltageCircled/></ListItemIcon>
                <ListItemText primary={'Input Volt.'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                    primary={
                        <span>
                            <ChannelValue value={478} units={'V'} />, <ChannelValue value={479} units={'V'} />, <ChannelValue value={473} units={'V'} />
                        </span>
                    } 
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
            <ListItem divider style={{color: Colors.red['500']}}>
                <ListItemIcon style={{color: 'inherit'}}><VoltageCircled /></ListItemIcon>
                <ListItemText primary={'Output Voltage'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                    primary={
                        <span>
                            <ChannelValue value={480} units={'V'} />, <ChannelValue value={480} units={'V'} />, <ChannelValue value={480} units={'V'} />
                        </span>
                    } 
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
            <ListItem divider>
                <ListItemIcon><CurrentCircled/></ListItemIcon>
                <ListItemText primary={'Output Current'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                    primary={
                        <span>
                            <ChannelValue value={15} units={'A'} />, <ChannelValue value={15} units={'A'} />, <ChannelValue value={14.9} units={'A'} />
                        </span>
                    } 
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
            <ListItem>
                <ListItemIcon><Temp/></ListItemIcon>
                <ListItemText primary={'Temperature'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                primary={<ChannelValue icon={<Trend nativeColor={Colors.red[500]}/>} value={68} units={'°F'} />}
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
        </List>
    </Card>
)
