// components/src/channel-value/channel-value.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'pxb-channel-value',
    template: `
        <span class="value-wrapper" [style.color]="color" [style.fontSize.px]="fontSize">
            <span class="icon">
                <ng-content></ng-content>
            </span>
            <h5 *ngIf="units && prefix" class="text units">{{ units }}</h5>
            <h5 *ngIf="value" class="text value">{{ value }}</h5>
            <h5 *ngIf="units && !prefix" class="text units">{{ units }}</h5>
        </span>
    `,
    styleUrls: ['./channel-value.component.scss'],
})
export class ChannelValueComponent {
    @Input() value: string;
    @Input() units: string;
    @Input() fontSize = 'inherit';
    @Input() prefix = false;
    @Input() color = 'inherit';
}

// react-native/components/src/channel-value.tsx
import React, { Component } from 'react';
import { Text, View } from 'react-native';

export interface ChannelValueProps {
  value: string | number;
  icon?: React.ReactNode;
  units?: string;
  prefix?: string;
  fontSize?: number;
  color?: string;
}

export class ChannelValue extends Component<ChannelValueProps> {
  public render() {
    const { value, icon, units, prefix, fontSize, color } = this.props;

    return (
      <View>
        {icon}
        <Text>{value}</Text>
        <Text>{units}</Text>
      </View>
    );
  }
}
