// react/component-demo/src/App.js
import React from 'react';
import Hero from '@pxblue/react-components/core/Hero';
import HeroBanner from '@pxblue/react-components/core/HeroBanner';
import ChannelValue from '@pxblue/react-components/core/ChannelValue';
import Trend from '@material-ui/icons/TrendingUp';
import Timer from '@material-ui/icons/Timer';

import { List, ListItem, ListItemIcon, ListItemText, Card } from '@material-ui/core';
import * as Colors from '@pxblue/colors';
import { Pie, Battery } from '@pxblue/react-progress-icons';
import { GradeA, Leaf, CurrentCircled, VoltageCircled, Temp } from '@pxblue/icons-mui';


export default ({ ...props }) => (
    <Card>
        <List style={{color: Colors.gray['800'], padding: 0}}>
            <HeroBanner divider>
                <Hero
                    icon={<GradeA fontSize={'inherit'} color={'inherit'} nativeColor={Colors.green[500]} />}
                    label={'Healthy'}
                    value={96}
                    units={'/100'}
                    fontSize={'normal'}
                />
                <Hero
                    icon={<Pie color={Colors.blue[500]} percent={65} size={36} />}
                    label={'Load'}
                    fontSize={'normal'}
                >
                    <ChannelValue value={65} units={'%'} icon={<Trend nativeColor={Colors.red[500]} fontSize={'inherit'} />} />
                </Hero>
                <Hero
                    icon={<Timer fontSize={'inherit'} color={'inherit'} />}
                    label={'Estimated'}
                    fontSize={'normal'}
                >
                    <ChannelValue value={1} units={'h'} />
                    <ChannelValue value={26} units={'m'} />
                </Hero>
                <Hero
                    icon={<Battery color={Colors.blue[500]} percent={100} size={36} />}
                    value={'Full'}
                    label={'Battery'}
                    fontSize={'normal'}
                >
                    <ChannelValue value={'Full'} />
                </Hero>
            </HeroBanner>
            <ListItem divider>
                <ListItemIcon><Leaf/></ListItemIcon>
                <ListItemText primary={'Status'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                    primary={<ChannelValue value={'Online, ESS+'} />} 
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
            <ListItem divider>
                <ListItemIcon><VoltageCircled/></ListItemIcon>
                <ListItemText primary={'Input Volt.'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                    primary={
                        <span>
                            <ChannelValue value={478} units={'V'} />, <ChannelValue value={479} units={'V'} />, <ChannelValue value={473} units={'V'} />
                        </span>
                    } 
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
            <ListItem divider style={{color: Colors.red['500']}}>
                <ListItemIcon style={{color: 'inherit'}}><VoltageCircled /></ListItemIcon>
                <ListItemText primary={'Output Voltage'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                    primary={
                        <span>
                            <ChannelValue value={480} units={'V'} />, <ChannelValue value={480} units={'V'} />, <ChannelValue value={480} units={'V'} />
                        </span>
                    } 
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
            <ListItem divider>
                <ListItemIcon><CurrentCircled/></ListItemIcon>
                <ListItemText primary={'Output Current'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                    primary={
                        <span>
                            <ChannelValue value={15} units={'A'} />, <ChannelValue value={15} units={'A'} />, <ChannelValue value={14.9} units={'A'} />
                        </span>
                    } 
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
            <ListItem>
                <ListItemIcon><Temp/></ListItemIcon>
                <ListItemText primary={'Temperature'} primaryTypographyProps={{color: 'inherit'}}></ListItemText>
                <ListItemText 
                    style={{padding: 0}}
                primary={<ChannelValue icon={<Trend nativeColor={Colors.red[500]}/>} value={68} units={'°F'} />}
                    primaryTypographyProps={{color: 'inherit', style: {textAlign: 'right'}}}>
                </ListItemText>
            </ListItem>
        </List>
    </Card>
)

// angular/component-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { MatIconRegistry } from "@angular/material/icon";
import { DomSanitizer } from "@angular/platform-browser";
declare var require: any;
const iconSet = require("@pxblue/icons-svg/icons.svg");

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor(
    private matIconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer
  ) {
    this.matIconRegistry.addSvgIconSetInNamespace('px-icons', this.domSanitizer.bypassSecurityTrustResourceUrl(iconSet));
  }
}

<mat-card>
  <mat-list>
    <pxb-hero-banner [divider]="true" >
      <pxb-hero [allowClick]="true" label="Healthy" value="96"  units="/100" (click)="test()"  >
        <mat-icon svgIcon="px-icons:bearing" primary></mat-icon>
        <mat-icon  class="output" secondary>trending_up</mat-icon>
        
      </pxb-hero>

      <pxb-hero [allowClick]="true" label="Load" fontSize="small" >
        <pie-progress class="progress-icon" percent="70" size="36" primary></pie-progress>
        <pxb-channel-value class="content" value="65"  units="%" [prefix]="true"  >
          <mat-icon  class="output" >trending_up</mat-icon>
        </pxb-channel-value>
      </pxb-hero>

      <pxb-hero [allowClick]="true" label="Estimated" >
        <mat-icon primary>alarm</mat-icon>
        <pxb-channel-value class="content" value="1" units="h"></pxb-channel-value>
        <pxb-channel-value class="content" value="26" units="m"></pxb-channel-value>
      </pxb-hero>

      <pxb-hero [allowClick]="true" label="Battery"   value="Full" fontSize="small">
        <battery-progress class="progress-icon" percent="90" size="36" primary></battery-progress>
      </pxb-hero>

    </pxb-hero-banner>
  </mat-list>

  <mat-list >
    <mat-list-item >
        <mat-icon mat-list-icon  svgIcon="px-icons:leaf" class="list-icon"></mat-icon>
      <h4 mat-line>status</h4>
      <div class="channelcontent"> 
          <pxb-channel-value class="content list-value" value="online,ESS+"></pxb-channel-value>
      </div>
        
    </mat-list-item>
    <mat-divider></mat-divider>

    <mat-list-item >
        <mat-icon mat-list-icon svgIcon="px-icons:voltage_circled" class="list-icon"></mat-icon>
        <h4 mat-line>Input Voltage</h4>
        <div class="channelcontent">
        <pxb-channel-value class="content list-value" value="478" units="V"></pxb-channel-value>,
        <pxb-channel-value class="content list-value" value="479" units="V"></pxb-channel-value>,
        <pxb-channel-value class="content list-value" value="473" units="V"></pxb-channel-value>
        </div>
      </mat-list-item>
      <mat-divider></mat-divider>

    <mat-list-item class="output">
        <mat-icon mat-list-icon svgIcon="px-icons:voltage_circled" class="list-icon" color="red"></mat-icon>
        <h4 mat-line>Output Voltage</h4>
        <div class="channelcontent">
        <pxb-channel-value class="content list-value" value="480" units="V"></pxb-channel-value>,
        <pxb-channel-value class="content list-value" value="480" units="V"></pxb-channel-value>,
        <pxb-channel-value class="content list-value" value="480" units="V"></pxb-channel-value>
        </div>
      </mat-list-item>
      <mat-divider></mat-divider>

    <mat-list-item >
        <mat-icon mat-list-icon svgIcon="px-icons:current_circled" class="list-icon" color="red"></mat-icon>
        <h4 mat-line>Output Current</h4>
        <div class="channelcontent">
        <pxb-channel-value class="content list-value" value="15" units="A"></pxb-channel-value>,
        <pxb-channel-value class="content list-value" value="15" units="A"></pxb-channel-value>,
        <pxb-channel-value class="content list-value" value="15" units="A"></pxb-channel-value>
        </div>
      </mat-list-item>
      <mat-divider></mat-divider>

      <mat-list-item >
          <mat-icon mat-list-icon svgIcon="px-icons:temp" class="list-icon" color="red"></mat-icon>
          <h4 mat-line>Temperature</h4>
          <div class="channelcontent">
          <pxb-channel-value class="content" value="68"  units="°F">
              <mat-icon >trending_up</mat-icon>
            </pxb-channel-value>
          </div>
        </mat-list-item>
  </mat-list>


</mat-card>
